language: generic
sudo: required
dist: trusty

branches:
  only:
    - master

before_install:
  - ./scripts/prep-workspace

install:
  - ./src/scripts/install-ceres
  - ./src/scripts/install-ros
  - source ~/.bashrc

before_script:
  - pip install -q --user travis-sphinx

script:
  - ./src/scripts/setup-workspace
  - source ~./bashrc
  - cd $TRAVIS_BUILD_DIR
  - travis-sphinx build

after_success:
  - travis-sphinx deploy

notifications:
  email: false
  slack: osu-uwrt:QiKTeRcKbKhS82FG4s1SGMb6
