language: generic
sudo: required
dist: trusty

env:
  - ROS_DISTRO=indigo
branches:
  only:
    - travis
install:
  - pip install -q --user travis-sphinx
script:
  - travis-sphinx --source=docs build
after_success:
  - travis-sphinx deploy
notifications:
  email: false
#  slack: osu-uwrt:QiKTeRcKbKhS82FG4s1SGMb6
