language: generic
sudo: required
dist: trusty

env:
  - ROS_DISTRO=indigo

install:
  - ./scripts/install-ceres
  - ./scripts/install-ros

script:
  - source ~/.bashrc

notifications:
  email: false
  slack: osu-uwrt:QiKTeRcKbKhS82FG4s1SGMb6
