language: generic
sudo: required
dist: trusty

branches:
  only:
    - master

before_install:
  - ./scripts/workspace-prep

install:
  - ./scripts/install-ros
  - ./scripts/install-ceres
  - source ~/.bashrc

before_script:
  - ./scripts/install-sphinx

script:
  - ./scripts/workspace-setup
  - source ~/.bashrc
  - cd ~/osu-uwrt/riptide_ws
  - catkin_make
  - cd $TRAVIS_BUILD_DIR
  - travis-sphinx build

after_success:
  - travis-sphinx deploy

notifications:
  email: false
  # slack: osu-uwrt:QiKTeRcKbKhS82FG4s1SGMb6
