language: generic
sudo: required
dist: trusty

env:
  - ROS_DISTRO=indigo
#  - ROS_DISTRO=jade

branches:
  only:
    - master

before_install:
  - pip install -q --user travis-sphinx
  - ./scripts/install-ceres
  - ./scripts/install-ros
  - source ~/.bashrc

install:
  - ./scripts/create-workspace
  - ./scripts/move-repo
  - source ~/.bashrc

script:
  - cd ~/osu-uwrt/riptide_ws
  - catkin_make
  - cd $TRAVIS_BUILD_DIR
  - travis-sphinx build

after_success:
  - travis-sphinx deploy

notifications:
  email: false
#  slack: osu-uwrt:QiKTeRcKbKhS82FG4s1SGMb6
