language: generic
sudo: required
dist: trusty

branches:
  only:
    - master

install:
  - source ~/.bashrc

script:
  - source ~/.bashrc

notifications:
  email: false
  # slack: osu-uwrt:QiKTeRcKbKhS82FG4s1SGMb6
