language: generic
sudo: required
dist: trusty

branches:
  only:
    - master

before_install:
  - ./scripts/copy-to-workspace
  - source ~/.bashrc

install:
  - ./scripts/install-ceres
  - ./scripts/install-ros
  - source ~/.bashrc

before_script:
  - pip install -q --user travis-sphinx

script:
  - catkin_make
  - cd $TRAVIS_BUILD_DIR
  - travis-sphinx build

after_success:
  - travis-sphinx deploy

notifications:
  email: false
  slack: osu-uwrt:QiKTeRcKbKhS82FG4s1SGMb6
