language: generic
sudo: required
dist: trusty

env:
  - ROS_DISTRO=indigo
  - ROS_DISTRO=jade

install:
  - ./ceres-install
  - ./ros-install-max

script:
  - source ~/.bashrc

notifications:
  email: false
  slack: osu-uwrt:QiKTeRcKbKhS82FG4s1SGMb6
